# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none
#- main

pool:
  #vmImage: ubuntu-latest
  name: LinuxAgentPool





steps:

- task: NodeTool@0
  displayName: 'Install Node Tools'
  inputs:
    versionSource: 'spec'
    versionSpec: '18.x'
    checkLatest: true


- task: CmdLine@2
  displayName: 'Install CDK'
  inputs:
    script: 'npm install -g aws-cdk'

- task: CmdLine@2
  displayName: 'Install AWS .NET Lambda Tools'
  inputs:
    script: 'dotnet tool install -g Amazon.Lambda.Tools'



- task: AWSShellScript@1
  displayName: 'Deploy CDK Stack'
  inputs:
    awsCredentials: 'AWS-Dotnet-Ohio'
    regionName: 'us-east-2'
    scriptType: 'inline'
    inlineScript: |
      chmod +x ./build.sh
      cdk deploy --build ./build.sh --context stackName=$(stackname) --context environmentName=$(environmentName) --context account=$(account) --context region=$(region)
    disableAutoCwd: true
    workingDirectory: 'serverless-doc-processing'
