version = 0.1
[default.deploy.parameters]
stack_name = "test-app19"
resolve_s3 = true
s3_prefix = "test-app19"
region = "us-east-2"
capabilities = "CAPABILITY_IAM"
disable_rollback = true
parameter_overrides = "BootstrapVersion=\"/cdk-bootstrap/hnb659fds/version\""
image_repositories = []
